### ISSUE TITLE
Highlight aligned TN for the currently active TN

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/create-app#36]
When a user navigates to a new verse and associated TNs are displayed in the TN card the scripture text that's quoted in the TN should be highlighted in the scripture card. https://projects.invisionapp.com/share/6VZ7U05QCMN#/screens/435786500

**Comment by mannycolon** [comment]
Should we highlight the quote when clicking it? How do we prioritize tn/tw quote highlighting?
