### ISSUE TITLE
Initialization of Book Package in the app

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/create-app#7]
As a user, I want to choose a book package as per the following steps:
1. Login to the app using DCS credentials. If No DCS credentials exist, should be directed to create a DCS account.
2. Choose my organization. If the organization does not exist, should be directed to contact admin.
3. Choose my language. 
4. Choose the Book. Books in scope- OT, NT, [OBS (Create 2.1)]
Once I select the book, I should be able to review the book package in a harmonized manner. 
For OT or NT- Book Package to include ULT, UST, tA, tN, tW,tQ.

If any of the resources are unavailable in the selected Book Package, the appropriate error message should be indicated in the related Helps card.

---------
(Waiting for 2.1) For OBS - Book Package to include OBS, OBS translation notes, OBS questions and OBS Words. (study Notes- TBD)

**Comment by PhotoNomad0** [comment]
Questions:
It seems that the changes required are:
- We need to add book selection to the stepper
  - does this mean that if a book is selected the user can still navigate to a different book?
- It also looks like we have add OBS support
 
What else needs to change?

**Comment by birchamp** [comment]
The ability to change the book is always at the top of the screen.
OBS has been broken out into #66
