### ISSUE TITLE
SPIKE: Try out more flexible TSV view for TN

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/create-app#72]
Experiment with a 2 column format for TN and a card that will handle both the old and new TN TSV formats

DoD: Both old (test_org2) and new (test_org) TSV formats can be opened in the TN card

**Comment by mannycolon** [comment]
@birchamp That's not what I meant yesterday, I meant that the current card could handle both old and new format but not render both at the same time

**Comment by birchamp** [comment]
@mannycolon edited the issue.  I was trying not to lose your idea of using the 2 column format to handle the smaller text fields. Definitely not showing both at the same time

**Comment by cckozie** [comment]
I logged in as tcc001 which took me to the last used project, Titus
I opened the drawer, selected the option to change account settings, then  changed the org from test_org to test_org2
After clicking the Save and Continue button I saw this screen:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/994f25d9-c7d3-4305-a589-88f342f9f89e)

**Comment by mannycolon** [comment]
@cckozie Is this bug related to the issue though?

**Comment by cckozie** [comment]
Created issue #124 to deal with this problem.
Closing since this is a spike.
